# Generated by Django 3.0.3 on 2020-04-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20200409_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_day',
            field=models.CharField(blank=True, default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_month',
            field=models.CharField(blank=True, default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='date_year',
            field=models.CharField(blank=True, default='', max_length=4),
            preserve_default=False,
        ),
    ]
